CREATE TABLE LESER(LNr NUMBER(5, 0), Name VARCHAR2(100),  Adresse VARCHAR2(250)
    ,GebDatum DATE, KNr NUMBER(5, 0), KontoSeit DATE);
    
ALTER TABLE LESER MODIFY (LNr NOT NULL);
ALTER TABLE LESER MODIFY (KNr NOT NULL);
ALTER TABLE LESER ADD (CONSTRAINT PK_LESER PRIMARY KEY (LNr));

CREATE TABLE KONTOSTATUS (KNr NUMBER(5, 0), BuecherAusgeliehen NUMBER(2, 0),
    BuecherUeberzogen NUMBER(2, 0), FehlendeGebuehrenHoehe NUMBER(5, 0));
    
ALTER TABLE KONTOSTATUS MODIFY (KNr NOT NULL);
ALTER TABLE KONTOSTATUS ADD (CONSTRAINT PK_KONTOSTATUS PRIMARY KEY (KNr));

CREATE TABLE BUCH (ISBN VARCHAR2(20), Titel VARCHAR2(200), Jahr NUMBER(4,0),
    VOrt VARCHAR2(100), VName VARCHAR2(100), BName VARCHAR2(250), Anzahl NUMBER(5, 0));

ALTER TABLE BUCH MODIFY (ISBN NOT NULL);
ALTER TABLE BUCH ADD (CONSTRAINT PK_BUCH PRIMARY KEY (ISBN));

CREATE TABLE BUCHSTATUS (ISBN VARCHAR2(20), VerfuegbarAnzahl NUMBER(2, 0),
    ReserviertAnzahl NUMBER(2, 0), AusgeliehenAnzahl NUMBER(2, 0));

ALTER TABLE BUCHSTATUS MODIFY (ISBN NOT NULL);
ALTER TABLE BUCHSTATUS ADD (CONSTRAINT PK_BUCHSTATUS PRIMARY KEY (ISBN));

CREATE TABLE RECHERCHE (LNr NUMBER(5, 0), ISBN VARCHAR2(20), Stichwort VARCHAR2(200),
    RTitel VARCHAR2(200), RAutor VARCHAR2(100));
    
ALTER TABLE RECHERCHE MODIFY (LNr NOT NULL);
ALTER TABLE RECHERCHE MODIFY (ISBN NOT NULL);
ALTER TABLE RECHERCHE ADD (CONSTRAINT PK_RECHERCHE PRIMARY KEY (LNr, ISBN));

CREATE TABLE MAHNUNG (KNr NUMBER(5, 0), BName VARCHAR2(250), Grund VARCHAR2(250));

ALTER TABLE MAHNUNG MODIFY (KNr NOT NULL);
ALTER TABLE MAHNUNG MODIFY (BName NOT NULL);

CREATE TABLE ZAHLEN (LNr NUMBER(5, 0), BName VARCHAR2(200), Hoehe NUMBER(5, 0),
    Grund VARCHAR2(200));
    
ALTER TABLE ZAHLEN MODIFY (LNr NOT NULL);
ALTER TABLE ZAHLEN MODIFY (BName NOT NULL);
ALTER TABLE ZAHLEN ADD(CONSTRAINT PK_ZAHLEN PRIMARY KEY (LNr, BName));

CREATE TABLE AKTION (KNr NUMBER(5, 0), ISBN VARCHAR2(20),
    Reservieren NUMBER(1, 0), Ausleihen NUMBER(1, 0), Ueberzogen NUMBER(1, 0));

ALTER TABLE AKTION MODIFY (KNr NOT NULL);
ALTER TABLE AKTION MODIFY (ISBN NOT NULL);
ALTER TABLE AKTION ADD (CONSTRAINT PK_AKTION PRIMARY KEY (KNr, ISBN));
ALTER TABLE AKTION MODIFY (Reservieren DEFAULT 0);
ALTER TABLE AKTION MODIFY (Ausleihen DEFAULT 0);
ALTER TABLE AKTION MODIFY (Ueberzogen DEFAULT 0);
    
